### ISSUE TITLE
btn is not show when scroll up and down in faster

### ISSUE THREAD

**Issue by neilqin** [oonne/yii2-scroll-to-top#1]
btn is not show when scroll up and down in faster,so i change the js file，can you able to update?
scroll-top.js,code is below,add variable scrollBtnIsvisible to control the btn to show:

$(function(){  
    
    var btn = $('#scroll-to-top');
    var scrollBtnIsvisible=false;
    var scrollerTriggerPoint = $('html, body').offset().top + 50;
    $(document).on('scroll', function() {
        var pos = $(window).scrollTop();
        if (pos > scrollerTriggerPoint && !scrollBtnIsvisible) {
            btn.stop().fadeIn();
            scrollBtnIsvisible = true;
        } else if (pos < scrollerTriggerPoint && scrollBtnIsvisible) {
            btn.stop().fadeOut();
            scrollBtnIsvisible = false;
        }
    }).scroll();

    btn.on('click', function(e) {
        $('html, body').animate({ scrollTop: 0 }, 300);
    });
    
});

**Comment by oonne** [comment]
Thanks, for your contribution
